/**
 * Capacitor plugin interface for the Braze SDK.
 *
 * See https://github.com/bma342/capacitor-braze for full docs.
 *
 * Scope discipline: this interface only grows per the version roadmap in
 * `SDK_SURFACE.md`. New methods are scope decisions, not casual additions.
 */

/**
 * Options passed to `Braze.initialize`.
 *
 * `apiKey` is a **public Braze SDK API key** (the kind embedded in your app).
 * Never pass a REST API key here — they are different things. See SECURITY.md §1.
 */
export interface BrazeInitializeOptions {
  /** Braze SDK API key (public). */
  apiKey: string;
  /** Braze SDK endpoint, e.g. `sdk.iad-03.braze.com`. Must be HTTPS in production. */
  endpoint: string;
  /** Enable verbose SDK logging. Defaults to `false`. Never enable in production. */
  enableLogging?: boolean;
  /** Enable SDK Authentication (signed JWT validation). Strongly recommended for production. */
  enableSdkAuthentication?: boolean;
  /** Allow non-HTTPS `endpoint` (for local mock-server testing only). Defaults to `false`. */
  allowInsecureEndpoint?: boolean;
}

export interface BrazeEchoOptions {
  value: string;
}

export interface BrazeEchoResult {
  value: string;
}

/**
 * Identifies the current user to Braze. Subsequent events are attributed to
 * this user. If SDK Authentication is enabled, `sdkAuthSignature` is required
 * — see SECURITY.md §2.
 */
export interface BrazeChangeUserOptions {
  /** Your application's unique identifier for this user. */
  userId: string;
  /** JWT signature generated by your backend, signed with your private key. */
  sdkAuthSignature?: string;
}

/**
 * Property values supported for Braze custom events. Braze accepts strings,
 * numbers, booleans, and dates; v0.1 supports the first three. Date support
 * lands in a later version (see SDK_SURFACE.md §2).
 */
export type BrazeEventPropertyValue = string | number | boolean;

export type BrazeEventProperties = Record<string, BrazeEventPropertyValue>;

export interface BrazeLogCustomEventOptions {
  /** Event name. Max length is enforced by the Braze backend. */
  name: string;
  /** Optional event properties. Up to ~100 keys per Braze docs. */
  properties?: BrazeEventProperties;
}

export interface BrazePlugin {
  /**
   * Round-trips a value through the native bridge. Used to verify plugin
   * installation and bridge health. Not a Braze SDK method.
   *
   * @example
   * const { value } = await Braze.echo({ value: 'hello' });
   * // value === 'hello'
   */
  echo(options: BrazeEchoOptions): Promise<BrazeEchoResult>;

  /**
   * Initialize the Braze SDK. Must be called before any other Braze method.
   *
   * @example
   * await Braze.initialize({
   *   apiKey: 'YOUR-SDK-KEY',
   *   endpoint: 'sdk.iad-03.braze.com',
   *   enableSdkAuthentication: true,
   * });
   */
  initialize(options: BrazeInitializeOptions): Promise<void>;

  /**
   * Identifies the current user. Call after `initialize`. Pass an
   * `sdkAuthSignature` if SDK Authentication is enabled.
   *
   * @example
   * await Braze.changeUser({
   *   userId: 'user_123',
   *   sdkAuthSignature: '<jwt-from-your-backend>',
   * });
   */
  changeUser(options: BrazeChangeUserOptions): Promise<void>;

  /**
   * Logs a custom event for the current user.
   *
   * @example
   * await Braze.logCustomEvent({
   *   name: 'cart_viewed',
   *   properties: { items: 3, value: 42.99 },
   * });
   */
  logCustomEvent(options: BrazeLogCustomEventOptions): Promise<void>;
}
