/**
 * Capacitor plugin interface for the Braze SDK.
 *
 * See https://github.com/bma342/capacitor-braze for full docs.
 *
 * Scope discipline: this interface only grows per the version roadmap in
 * `SDK_SURFACE.md`. New methods are scope decisions, not casual additions.
 */

// =============================================================================
// Configuration
// =============================================================================

/**
 * Options passed to {@link BrazePlugin.initialize}.
 *
 * `apiKey` is a **public Braze SDK API key** (the kind embedded in your app).
 * Never pass a REST API key here — they are different things. See `SECURITY.md` §1.
 */
export interface BrazeInitializeOptions {
  /** Braze SDK API key (public). */
  apiKey: string;
  /**
   * Braze SDK endpoint, e.g. `sdk.iad-03.braze.com`. Must be HTTPS in production.
   * For mock-server testing, set {@link BrazeInitializeOptions.allowInsecureEndpoint}.
   */
  endpoint: string;
  /**
   * Enable verbose SDK logging. Defaults to `false`. Never enable in production
   * builds — Braze SDK logs include event payloads which may contain PII.
   * See `SECURITY.md` §8.
   */
  enableLogging?: boolean;
  /**
   * Enable SDK Authentication (signed JWT validation). **Strongly recommended for
   * production.** Without it, anyone with the public SDK API key can spoof events
   * for arbitrary user IDs. See `SECURITY.md` §2 for the full design.
   */
  enableSdkAuthentication?: boolean;
  /**
   * Allow non-HTTPS `endpoint`. Defaults to `false` and should remain so in
   * production. Only set `true` for local mock-server testing per `SECURITY.md` §4.
   */
  allowInsecureEndpoint?: boolean;
}

// =============================================================================
// Bridge sanity check
// =============================================================================

export interface BrazeEchoOptions {
  /** Arbitrary string round-tripped through the native bridge. */
  value: string;
}

export interface BrazeEchoResult {
  /** The same `value` passed in, returned by the native bridge unchanged. */
  value: string;
}

// =============================================================================
// User identity
// =============================================================================

/**
 * Options for {@link BrazePlugin.changeUser}. Identifies the current user to
 * Braze; subsequent events and attributes are attributed to this user.
 */
export interface BrazeChangeUserOptions {
  /**
   * Your application's unique identifier for this user. Often an internal
   * user ID; treat as PII even if it isn't directly readable as one.
   */
  userId: string;
  /**
   * JWT signature generated by your backend, signed with your private key.
   * Required when SDK Authentication is enabled. See `SECURITY.md` §2.
   */
  sdkAuthSignature?: string;
}

// =============================================================================
// Custom events
// =============================================================================

/**
 * Property value types accepted by Braze custom events. v0.1 supports primitive
 * scalars (string / number / boolean). Date and array support land in a later
 * version per `SDK_SURFACE.md` §2.
 */
export type BrazeEventPropertyValue = string | number | boolean;

/** Map of event property names to primitive values. */
export type BrazeEventProperties = Record<string, BrazeEventPropertyValue>;

export interface BrazeLogCustomEventOptions {
  /** Event name. Max length enforced by the Braze backend (~255 chars). */
  name: string;
  /** Optional event properties. Braze accepts up to ~100 keys per event. */
  properties?: BrazeEventProperties;
}

// =============================================================================
// Privacy / lifecycle
// =============================================================================

export interface BrazeIsDisabledResult {
  /** `true` if {@link BrazePlugin.disableSDK} has been called and not re-enabled. */
  disabled: boolean;
}

// =============================================================================
// Plugin interface
// =============================================================================

export interface BrazePlugin {
  /**
   * Round-trips a value through the native bridge. Useful as a sanity check
   * that the plugin installed correctly on the current platform. Not a Braze
   * SDK method.
   *
   * @example
   * const { value } = await Braze.echo({ value: 'hello' });
   * // value === 'hello'
   */
  echo(options: BrazeEchoOptions): Promise<BrazeEchoResult>;

  /**
   * Initialize the Braze SDK. **Must be called before any other Braze method**
   * (except {@link BrazePlugin.echo}, {@link BrazePlugin.wipeData},
   * {@link BrazePlugin.disableSDK}, {@link BrazePlugin.enableSDK}, and
   * {@link BrazePlugin.isDisabled}, all of which are init-independent).
   *
   * @example
   * await Braze.initialize({
   *   apiKey: 'YOUR-SDK-KEY',
   *   endpoint: 'sdk.iad-03.braze.com',
   *   enableSdkAuthentication: true,
   * });
   */
  initialize(options: BrazeInitializeOptions): Promise<void>;

  /**
   * Identifies the current user. Pass an `sdkAuthSignature` if SDK
   * Authentication is enabled (see `SECURITY.md` §2).
   *
   * @example
   * await Braze.changeUser({
   *   userId: 'user_123',
   *   sdkAuthSignature: '<jwt-from-your-backend>',
   * });
   */
  changeUser(options: BrazeChangeUserOptions): Promise<void>;

  /**
   * Logs a custom event for the current user.
   *
   * @example
   * await Braze.logCustomEvent({
   *   name: 'cart_viewed',
   *   properties: { items: 3, value: 42.99 },
   * });
   */
  logCustomEvent(options: BrazeLogCustomEventOptions): Promise<void>;

  /**
   * **Destructive.** Removes all locally stored Braze SDK data on the device,
   * including the device ID and any queued unsent events.
   *
   * Typical use: GDPR Article 17 right-to-be-forgotten flow, or on user
   * logout. After wiping, you almost always also want to:
   * 1. Call your backend's Braze REST `/users/delete` to remove server-side
   *    profile data.
   * 2. Revoke the user's SDK Authentication signature.
   *
   * See `SECURITY.md` §10 for the complete privacy flow.
   *
   * Init-independent: safe to call before {@link BrazePlugin.initialize}.
   *
   * @example
   * // On logout:
   * await Braze.wipeData();
   *
   * @example
   * // Right-to-be-forgotten:
   * await Braze.wipeData();              // local
   * await myBackend.brazeDelete(userId); // server
   */
  wipeData(): Promise<void>;

  /**
   * Halts all data collection by the Braze SDK. No further events or
   * attributes are sent to Braze until {@link BrazePlugin.enableSDK} is called.
   *
   * Typical use: user revokes marketing consent under GDPR/CCPA without
   * fully wiping their data.
   *
   * Init-independent: safe to call before {@link BrazePlugin.initialize}.
   *
   * @example
   * // User opts out of marketing tracking
   * await Braze.disableSDK();
   */
  disableSDK(): Promise<void>;

  /**
   * Re-enables the Braze SDK after a {@link BrazePlugin.disableSDK} call.
   * No-op if the SDK was not previously disabled.
   *
   * Init-independent: safe to call before {@link BrazePlugin.initialize}.
   *
   * @example
   * // User restores consent
   * await Braze.enableSDK();
   */
  enableSDK(): Promise<void>;

  /**
   * Returns whether the SDK is currently disabled.
   *
   * Init-independent: safe to call before {@link BrazePlugin.initialize}.
   *
   * @example
   * const { disabled } = await Braze.isDisabled();
   * if (disabled) console.log('Tracking is paused');
   */
  isDisabled(): Promise<BrazeIsDisabledResult>;

  /**
   * Forces an immediate flush of any queued events to Braze. Normally Braze
   * batches network requests; this bypasses batching.
   *
   * Useful for: (1) Layer 4 smoke testing where you want events to appear in
   * the dashboard immediately, (2) edge cases where app may be killed before
   * the next batch.
   *
   * Requires {@link BrazePlugin.initialize} to have been called.
   *
   * @example
   * await Braze.logCustomEvent({ name: 'critical_event' });
   * await Braze.requestImmediateDataFlush(); // don't wait for batch
   */
  requestImmediateDataFlush(): Promise<void>;
}
