/**
 * Capacitor plugin interface for the Braze SDK.
 *
 * See https://github.com/bma342/capacitor-braze for full docs.
 *
 * Scope discipline: this interface only grows per the version roadmap in
 * `SDK_SURFACE.md`. New methods are scope decisions, not casual additions.
 */

import type { PluginListenerHandle } from '@capacitor/core';

// =============================================================================
// Configuration
// =============================================================================

/**
 * Options passed to {@link BrazePlugin.initialize}.
 *
 * `apiKey` is a **public Braze SDK API key** (the kind embedded in your app).
 * Never pass a REST API key here — they are different things. See `SECURITY.md` §1.
 */
export interface BrazeInitializeOptions {
  /** Braze SDK API key (public). */
  apiKey: string;
  /**
   * Braze SDK endpoint, e.g. `sdk.iad-03.braze.com`. Must be HTTPS in production.
   * For mock-server testing, set {@link BrazeInitializeOptions.allowInsecureEndpoint}.
   */
  endpoint: string;
  /**
   * Enable verbose SDK logging. Defaults to `false`. Never enable in production
   * builds — Braze SDK logs include event payloads which may contain PII.
   * See `SECURITY.md` §8.
   */
  enableLogging?: boolean;
  /**
   * Enable SDK Authentication (signed JWT validation). **Strongly recommended for
   * production.** Without it, anyone with the public SDK API key can spoof events
   * for arbitrary user IDs. See `SECURITY.md` §2 for the full design.
   */
  enableSdkAuthentication?: boolean;
  /**
   * Allow non-HTTPS `endpoint`. Defaults to `false` and should remain so in
   * production. Only set `true` for local mock-server testing per `SECURITY.md` §4.
   */
  allowInsecureEndpoint?: boolean;
  /**
   * Session timeout in seconds. After this much inactivity, the SDK
   * opens a new session on the next event. Braze's default across all
   * three SDKs is 30 minutes (1800 seconds); supply a value here to
   * override. Must be a positive integer; values ≤ 0 are rejected.
   *
   * Cross-platform note: the plugin contract uses seconds across all
   * three platforms. iOS's underlying setter takes a `TimeInterval`
   * (a `Double` of seconds); the iOS bridge casts. Android and Web
   * take seconds directly with no conversion.
   */
  sessionTimeoutInSeconds?: number;
}

export interface BrazeSetSdkAuthenticationSignatureOptions {
  /**
   * New SDK Authentication signature (signed JWT) to push into the SDK.
   * Used to rotate the signature when the previous one expires or when
   * an `sdkAuthError` event has fired indicating the backend rejected
   * the previous token. See `SECURITY.md` §2.
   */
  signature: string;
}

// =============================================================================
// Bridge sanity check
// =============================================================================

export interface BrazeEchoOptions {
  /** Arbitrary string round-tripped through the native bridge. */
  value: string;
}

export interface BrazeEchoResult {
  /** The same `value` passed in, returned by the native bridge unchanged. */
  value: string;
}

// =============================================================================
// User identity
// =============================================================================

/**
 * Options for {@link BrazePlugin.changeUser}. Identifies the current user to
 * Braze; subsequent events and attributes are attributed to this user.
 */
export interface BrazeChangeUserOptions {
  /**
   * Your application's unique identifier for this user. Often an internal
   * user ID; treat as PII even if it isn't directly readable as one.
   */
  userId: string;
  /**
   * JWT signature generated by your backend, signed with your private key.
   * Required when SDK Authentication is enabled. See `SECURITY.md` §2.
   */
  sdkAuthSignature?: string;
}

export interface BrazeGetUserIdResult {
  /**
   * The current external user ID, or `null` if the user is still anonymous
   * (i.e. {@link BrazePlugin.changeUser} has not been called).
   */
  userId: string | null;
}

// =============================================================================
// User attributes (standard)
//
// Every standard setter accepts `string | null`. Passing null clears the
// attribute (matches native SDK semantics). All work against the current user,
// which defaults to an anonymous profile until `changeUser` is called.
// =============================================================================

export interface BrazeSetEmailOptions {
  /** Email address. Pass `null` to clear. */
  email: string | null;
}

export interface BrazeSetPhoneNumberOptions {
  /** Phone number, ideally E.164 format. Pass `null` to clear. */
  phoneNumber: string | null;
}

export interface BrazeSetFirstNameOptions {
  /** First name. Pass `null` to clear. */
  firstName: string | null;
}

export interface BrazeSetLastNameOptions {
  /** Last name. Pass `null` to clear. */
  lastName: string | null;
}

export interface BrazeSetLanguageOptions {
  /** ISO 639-1 language code, e.g. `"en"`. Pass `null` to clear. */
  language: string | null;
}

export interface BrazeSetCountryOptions {
  /** ISO 3166-1 alpha-2 country code, e.g. `"US"`. Pass `null` to clear. */
  country: string | null;
}

// =============================================================================
// User attributes (custom)
// =============================================================================

/**
 * Value types accepted by {@link BrazePlugin.setCustomUserAttribute} in v0.1.
 * Date and array support land in a later version per `SDK_SURFACE.md` §2.
 *
 * Note: numeric values may surface in the Braze dashboard as floats. To
 * preserve integer vs. float distinction, send `{ value: 42 }` (no decimal)
 * for integers and `{ value: 42.0 }` (or any value with decimal) for floats —
 * the native bridge dispatches each type to the appropriate Braze SDK overload.
 */
export type BrazeAttributeValue = string | number | boolean;

export interface BrazeSetCustomUserAttributeOptions {
  /** Attribute key. Max length / character constraints enforced by Braze backend. */
  key: string;
  /** Attribute value. Use `setCustomUserAttribute` to remove via wipeData. */
  value: BrazeAttributeValue;
}

// =============================================================================
// Subscription groups
// =============================================================================

export interface BrazeSubscriptionGroupOptions {
  /**
   * The Braze-issued UUID of the subscription group. Find it in the Braze
   * dashboard under Subscription Group → API ID.
   */
  groupId: string;
}

// =============================================================================
// Aliases
// =============================================================================

export interface BrazeAddAliasOptions {
  /** Alias value. (alias, label) pairs are unique across users. */
  alias: string;
  /** Label / namespace for this alias, e.g. `"internal_id"`. */
  label: string;
}

// =============================================================================
// Device ID
// =============================================================================

export interface BrazeGetDeviceIdResult {
  /** The Braze SDK-assigned device identifier for the current install. */
  deviceId: string;
}

// =============================================================================
// Demographics
// =============================================================================

export interface BrazeSetDateOfBirthOptions {
  /** Four-digit year. */
  year: number;
  /** Month as 1-12 (January = 1). */
  month: number;
  /** Day of month, 1-31. */
  day: number;
}

/**
 * Gender values mirrored from the Braze SDK enums (Web `User.Genders`,
 * Android `com.braze.enums.Gender`, iOS `Braze.User.Gender`).
 */
export type BrazeGender = 'male' | 'female' | 'other' | 'unknown' | 'not_applicable' | 'prefer_not_to_say';

export interface BrazeSetGenderOptions {
  /** Gender value; see {@link BrazeGender}. */
  gender: BrazeGender;
}

export interface BrazeSetHomeCityOptions {
  /** Home city. Pass `null` to clear. */
  homeCity: string | null;
}

// =============================================================================
// Custom events
// =============================================================================

/**
 * Property value types accepted by Braze custom events. v0.1 supports primitive
 * scalars (string / number / boolean). Date and array support land in a later
 * version per `SDK_SURFACE.md` §2.
 */
export type BrazeEventPropertyValue = string | number | boolean;

/** Map of event property names to primitive values. */
export type BrazeEventProperties = Record<string, BrazeEventPropertyValue>;

export interface BrazeLogCustomEventOptions {
  /** Event name. Max length enforced by the Braze backend (~255 chars). */
  name: string;
  /** Optional event properties. Braze accepts up to ~100 keys per event. */
  properties?: BrazeEventProperties;
}

// =============================================================================
// Feature flags
// =============================================================================

/**
 * Wire-format shape of a single Braze feature flag property. Matches the
 * Web SDK's `PropertiesJson` entry type so the web path is zero-conversion;
 * native bridges serialize their typed property values into this shape.
 *
 * `'image'` is a URL string; `'datetime'` is a Unix timestamp in
 * milliseconds; `'jsonobject'` is a nested JSON object.
 */
export type BrazeFeatureFlagPropertyValue =
  | { type: 'string'; value: string }
  | { type: 'number'; value: number }
  | { type: 'boolean'; value: boolean }
  | { type: 'image'; value: string }
  | { type: 'datetime'; value: number }
  | { type: 'jsonobject'; value: Record<string, unknown> };

export interface BrazeFeatureFlag {
  /** Feature flag identifier as configured in the Braze dashboard. */
  id: string;
  /** Whether the flag is enabled for the current user. */
  enabled: boolean;
  /**
   * Map of property keys to typed property values. Empty for flags with no
   * configured properties.
   *
   * Cross-platform note: on Android and Web the properties are the raw
   * Braze wire format and arrive zero-conversion. On iOS the bridge
   * serializes BrazeKit's typed property enum into the same shape; if you
   * find an iOS-specific gap please file an issue.
   */
  properties: Record<string, BrazeFeatureFlagPropertyValue>;
}

export interface BrazeGetFeatureFlagOptions {
  /** Feature flag identifier. */
  id: string;
}

export interface BrazeGetFeatureFlagResult {
  /** The flag, or `null` if no flag with this `id` is configured. */
  flag: BrazeFeatureFlag | null;
}

export interface BrazeGetAllFeatureFlagsResult {
  /** All feature flags configured for the current user. */
  flags: BrazeFeatureFlag[];
}

export interface BrazeLogFeatureFlagImpressionOptions {
  /** Feature flag identifier whose impression should be logged. */
  id: string;
}

/**
 * Payload delivered to `'featureFlagsUpdated'` listeners. The full current
 * set of feature flags is included on every update; consumers should
 * treat this as a replacement, not a delta.
 */
export interface BrazeFeatureFlagsUpdatedEvent {
  flags: BrazeFeatureFlag[];
}

// =============================================================================
// Content cards
// =============================================================================

/**
 * Discriminator for the four content card variants. Mirrors the Web SDK
 * `Card` class hierarchy (`ClassicCard`, `CaptionedImage`, `ImageOnly`,
 * `ControlCard`) flattened to a string tag so the plugin's DTO survives
 * JSON serialization across the Capacitor bridge.
 */
export type BrazeContentCardType = 'classic' | 'captionedImage' | 'imageOnly' | 'control';

/**
 * Fields present on every content card regardless of type. Cross-platform
 * note: `updated` and `expiresAt` are Unix epoch milliseconds because the
 * Capacitor bridge can't JSON-serialize JS `Date` objects faithfully.
 * Web bridge converts via `.getTime()`; iOS / Android convert via the
 * SDK's millisecond accessors.
 */
export interface BrazeContentCardBase {
  /** Braze-issued card identifier. Used by impression / click logging. */
  id: string;
  /** Discriminator; narrow to a concrete card type with this field. */
  type: BrazeContentCardType;
  /** Whether the card has been shown to the user. */
  viewed: boolean;
  /** Whether the card is pinned to the top of the feed. */
  pinned: boolean;
  /** Custom key/value metadata configured in the Braze dashboard. */
  extras: Record<string, string>;
  /** Last modification time as Unix epoch ms; `null` if never modified. */
  updated: number | null;
  /** Expiry time as Unix epoch ms; `null` if no expiry. */
  expiresAt: number | null;
}

/**
 * Classic content card: title + description + optional image and click URL.
 * The most common card type.
 */
export interface BrazeClassicContentCard extends BrazeContentCardBase {
  type: 'classic';
  title: string;
  description: string;
  imageUrl?: string;
  url?: string;
  linkText?: string;
  clicked: boolean;
  dismissed: boolean;
  dismissible: boolean;
  language?: string;
  altImageText?: string;
}

/**
 * Card with a large image, title, and description text.
 */
export interface BrazeCaptionedImageContentCard extends BrazeContentCardBase {
  type: 'captionedImage';
  title: string;
  description: string;
  imageUrl: string;
  url?: string;
  linkText?: string;
  /** Aspect ratio hint for image loading. `null` when not provided. */
  aspectRatio: number | null;
  clicked: boolean;
  dismissed: boolean;
  dismissible: boolean;
  language?: string;
  altImageText?: string;
}

/**
 * Image-only card; no title or description.
 */
export interface BrazeImageOnlyContentCard extends BrazeContentCardBase {
  type: 'imageOnly';
  imageUrl: string;
  url?: string;
  aspectRatio: number | null;
  clicked: boolean;
  dismissed: boolean;
  dismissible: boolean;
  language?: string;
  altImageText?: string;
}

/**
 * Control card: represents a user enrolled in the control arm of a
 * content card multivariate test. Should be impression-logged but not
 * rendered as visible content.
 */
export interface BrazeControlContentCard extends BrazeContentCardBase {
  type: 'control';
}

/**
 * Tagged union over the four content card variants. Use the `type`
 * discriminator to narrow.
 *
 * @example
 * if (card.type === 'classic') console.log(card.title);
 */
export type BrazeContentCard =
  | BrazeClassicContentCard
  | BrazeCaptionedImageContentCard
  | BrazeImageOnlyContentCard
  | BrazeControlContentCard;

export interface BrazeGetContentCardsResult {
  /** All cards currently cached for the user. Empty if not yet fetched. */
  cards: BrazeContentCard[];
  /** Last-refresh time as Unix epoch ms; `null` if never fetched. */
  lastUpdated: number | null;
}

export interface BrazeLogContentCardClickOptions {
  /** Identifier of the card the user clicked. */
  cardId: string;
}

export interface BrazeLogContentCardImpressionOptions {
  /** Identifier of the card that was shown to the user. */
  cardId: string;
}

/**
 * Payload delivered to `'contentCardsUpdated'` listeners. Same shape as
 * {@link BrazeGetContentCardsResult}; the full current card set is
 * included on every update, not a delta.
 */
export interface BrazeContentCardsUpdatedEvent {
  cards: BrazeContentCard[];
  lastUpdated: number | null;
}

// =============================================================================
// Push token registration
// =============================================================================

export interface BrazeRegisterPushTokenOptions {
  /**
   * The platform-specific push token. On iOS this is the hex-encoded
   * APNs device token (the same string that `@capacitor/push-notifications`
   * emits in its `registration` event). On Android this is the FCM
   * registration token. Web does not have a comparable concept (Web Push
   * uses VAPID via the Push API + Service Worker, with no token to
   * register manually); calling on web throws.
   */
  token: string;
}

// =============================================================================
// Purchases
// =============================================================================

export interface BrazeLogPurchaseOptions {
  /**
   * Product identifier. Max ~255 chars, alphanumeric + punctuation. Cannot
   * begin with `$`. Enforced by the Braze backend.
   */
  productId: string;
  /**
   * ISO 4217 currency code, e.g. `"USD"`. Required by the plugin even where
   * the underlying Web SDK treats it as optional — having currency on every
   * purchase keeps revenue analytics consistent across platforms.
   */
  currency: string;
  /**
   * Per-unit price as a non-negative number in the currency's major units
   * (dollars, not cents). The Android bridge wraps to `BigDecimal`
   * internally.
   */
  price: number;
  /**
   * Number of units purchased. Defaults to `1`. Per Braze: integer in 1-100.
   */
  quantity?: number;
  /** Optional purchase properties (same shape as event properties). */
  properties?: BrazeEventProperties;
}

// =============================================================================
// Privacy / lifecycle
// =============================================================================

export interface BrazeIsDisabledResult {
  /** `true` if {@link BrazePlugin.disableSDK} has been called and not re-enabled. */
  disabled: boolean;
}

// =============================================================================
// Plugin interface
// =============================================================================

export interface BrazePlugin {
  // ---------------------------------------------------------------------------
  // Bridge sanity check
  // ---------------------------------------------------------------------------

  /**
   * Round-trips a value through the native bridge. Useful as a sanity check
   * that the plugin installed correctly on the current platform. Not a Braze
   * SDK method.
   *
   * @example
   * const { value } = await Braze.echo({ value: 'hello' });
   * // value === 'hello'
   */
  echo(options: BrazeEchoOptions): Promise<BrazeEchoResult>;

  // ---------------------------------------------------------------------------
  // Configuration
  // ---------------------------------------------------------------------------

  /**
   * Initialize the Braze SDK. **Must be called before any other Braze method**
   * except {@link BrazePlugin.echo} and the init-independent privacy/lifecycle
   * methods ({@link BrazePlugin.wipeData}, {@link BrazePlugin.disableSDK},
   * {@link BrazePlugin.enableSDK}, {@link BrazePlugin.isDisabled}).
   *
   * @example
   * await Braze.initialize({
   *   apiKey: 'YOUR-SDK-KEY',
   *   endpoint: 'sdk.iad-03.braze.com',
   *   enableSdkAuthentication: true,
   * });
   */
  initialize(options: BrazeInitializeOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // User identity
  // ---------------------------------------------------------------------------

  /**
   * Identifies the current user. Pass an `sdkAuthSignature` if SDK
   * Authentication is enabled (see `SECURITY.md` §2).
   *
   * @example
   * await Braze.changeUser({
   *   userId: 'user_123',
   *   sdkAuthSignature: '<jwt-from-your-backend>',
   * });
   */
  changeUser(options: BrazeChangeUserOptions): Promise<void>;

  /**
   * Returns the current external user ID, or `null` if the user is anonymous.
   *
   * @example
   * const { userId } = await Braze.getUserId();
   * if (!userId) await Braze.changeUser({ userId: 'user_123' });
   */
  getUserId(): Promise<BrazeGetUserIdResult>;

  /**
   * Rotates the SDK Authentication signature without re-running
   * `changeUser`. Use after the previous signature expires (typically
   * every 12-24h depending on your backend's JWT lifetime) or after
   * receiving an SDK Auth error from the Braze backend.
   *
   * Calling this without `enableSdkAuthentication: true` at init time
   * is a no-op in the SDK — the signature is stored but never sent.
   *
   * @example
   * // On a 401-style SDK auth failure or before expiry:
   * const signature = await myBackend.signBrazeSdkAuth(userId);
   * await Braze.setSdkAuthenticationSignature({ signature });
   */
  setSdkAuthenticationSignature(options: BrazeSetSdkAuthenticationSignatureOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // User attributes (standard)
  //
  // All setters work on the current user (anonymous or identified). Pass
  // `null` to clear an attribute. Email/phone are treated as PII per
  // SECURITY.md §3 — the plugin never logs them, even at debug level.
  // ---------------------------------------------------------------------------

  /**
   * Sets the current user's email.
   * @example
   * await Braze.setEmail({ email: 'jane@example.com' });
   * await Braze.setEmail({ email: null }); // clear
   */
  setEmail(options: BrazeSetEmailOptions): Promise<void>;

  /**
   * Sets the current user's phone number. E.164 format recommended.
   * @example
   * await Braze.setPhoneNumber({ phoneNumber: '+14155552671' });
   */
  setPhoneNumber(options: BrazeSetPhoneNumberOptions): Promise<void>;

  /**
   * Sets the current user's first name.
   * @example
   * await Braze.setFirstName({ firstName: 'Jane' });
   */
  setFirstName(options: BrazeSetFirstNameOptions): Promise<void>;

  /**
   * Sets the current user's last name.
   * @example
   * await Braze.setLastName({ lastName: 'Doe' });
   */
  setLastName(options: BrazeSetLastNameOptions): Promise<void>;

  /**
   * Sets the current user's language. Use ISO 639-1 codes.
   * @example
   * await Braze.setLanguage({ language: 'en' });
   */
  setLanguage(options: BrazeSetLanguageOptions): Promise<void>;

  /**
   * Sets the current user's country. Use ISO 3166-1 alpha-2 codes.
   * @example
   * await Braze.setCountry({ country: 'US' });
   */
  setCountry(options: BrazeSetCountryOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // User attributes (custom)
  // ---------------------------------------------------------------------------

  /**
   * Sets a custom user attribute. The native bridge dispatches based on the
   * inferred type of `value` (string / number / boolean → matching Braze SDK
   * overload).
   *
   * @example
   * await Braze.setCustomUserAttribute({ key: 'loyalty_tier', value: 'gold' });
   * await Braze.setCustomUserAttribute({ key: 'lifetime_orders', value: 12 });
   * await Braze.setCustomUserAttribute({ key: 'has_subscription', value: true });
   */
  setCustomUserAttribute(options: BrazeSetCustomUserAttributeOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Subscription groups
  // ---------------------------------------------------------------------------

  /**
   * Adds the current user to an email or SMS subscription group.
   *
   * @example
   * await Braze.addToSubscriptionGroup({ groupId: 'group-uuid-from-dashboard' });
   */
  addToSubscriptionGroup(options: BrazeSubscriptionGroupOptions): Promise<void>;

  /**
   * Removes the current user from a subscription group.
   *
   * @example
   * await Braze.removeFromSubscriptionGroup({ groupId: 'group-uuid' });
   */
  removeFromSubscriptionGroup(options: BrazeSubscriptionGroupOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Aliases
  // ---------------------------------------------------------------------------

  /**
   * Adds an alias for the current user. (alias, label) pairs are unique across
   * users — if another user already owns the pair, the alias is rejected by
   * the Braze backend.
   *
   * @example
   * await Braze.addAlias({ alias: 'cust_1234', label: 'internal_id' });
   */
  addAlias(options: BrazeAddAliasOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Device ID
  // ---------------------------------------------------------------------------

  /**
   * Returns the Braze SDK device identifier for the current install. Useful
   * for debugging and for sending the device ID to your backend for targeted
   * server-side messaging.
   *
   * Requires {@link BrazePlugin.initialize} to have been called. The accessor
   * is instance-bound on iOS (`braze.deviceId`) and Android
   * (`Braze.getInstance(context).deviceId`); only Web exposes a true static.
   * To keep the contract uniform across platforms (see C03 / C07) the plugin
   * gates this method behind the init guard on all three.
   *
   * @example
   * const { deviceId } = await Braze.getDeviceId();
   */
  getDeviceId(): Promise<BrazeGetDeviceIdResult>;

  // ---------------------------------------------------------------------------
  // Demographics
  // ---------------------------------------------------------------------------

  /**
   * Sets the current user's date of birth. `month` is 1-indexed (January = 1)
   * to match the Web SDK contract and to avoid the Java `Calendar.MONTH`
   * 0-indexed surprise. The Android bridge maps `month` to the Braze
   * `Month` enum internally.
   *
   * @example
   * await Braze.setDateOfBirth({ year: 1992, month: 7, day: 15 });
   */
  setDateOfBirth(options: BrazeSetDateOfBirthOptions): Promise<void>;

  /**
   * Sets the current user's gender. Accepts the string values listed in
   * {@link BrazeGender}; bridges map them to the matching native enum value.
   *
   * @example
   * await Braze.setGender({ gender: 'female' });
   */
  setGender(options: BrazeSetGenderOptions): Promise<void>;

  /**
   * Sets the current user's home city. Pass `null` to clear.
   *
   * @example
   * await Braze.setHomeCity({ homeCity: 'San Francisco' });
   */
  setHomeCity(options: BrazeSetHomeCityOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Custom events
  // ---------------------------------------------------------------------------

  /**
   * Logs a custom event for the current user.
   *
   * @example
   * await Braze.logCustomEvent({
   *   name: 'cart_viewed',
   *   properties: { items: 3, value: 42.99 },
   * });
   */
  logCustomEvent(options: BrazeLogCustomEventOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Purchases
  // ---------------------------------------------------------------------------

  /**
   * Logs a purchase. Required for Braze's revenue analytics. `currency` is
   * required on this contract even though the Web SDK accepts it optionally,
   * because revenue rolls up incorrectly when some events lack currency.
   *
   * @example
   * await Braze.logPurchase({
   *   productId: 'sku_42',
   *   currency: 'USD',
   *   price: 14.99,
   *   quantity: 1,
   *   properties: { coupon: 'WELCOME10' },
   * });
   */
  logPurchase(options: BrazeLogPurchaseOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Feature flags
  // ---------------------------------------------------------------------------

  /**
   * Returns a single feature flag by identifier, or `null` if no flag with
   * that `id` exists for the current user. Reads from the SDK's local
   * cache; call {@link BrazePlugin.refreshFeatureFlags} to force a fetch.
   *
   * @example
   * const { flag } = await Braze.getFeatureFlag({ id: 'checkout_v2' });
   * if (flag?.enabled) showNewCheckout();
   */
  getFeatureFlag(options: BrazeGetFeatureFlagOptions): Promise<BrazeGetFeatureFlagResult>;

  /**
   * Returns all feature flags currently cached for the user.
   *
   * @example
   * const { flags } = await Braze.getAllFeatureFlags();
   */
  getAllFeatureFlags(): Promise<BrazeGetAllFeatureFlagsResult>;

  /**
   * Requests an immediate refresh of feature flags from the Braze backend.
   * Fire-and-forget: the returned promise resolves once the refresh has
   * been dispatched, **not** once new flags arrive. Re-read with
   * {@link BrazePlugin.getAllFeatureFlags} after a short delay; the
   * subscribe-to-updates listener API will land in a later version.
   *
   * @example
   * await Braze.refreshFeatureFlags();
   * await new Promise(r => setTimeout(r, 1000));
   * const { flags } = await Braze.getAllFeatureFlags();
   */
  refreshFeatureFlags(): Promise<void>;

  /**
   * Logs an impression for a feature flag. Per Braze, limited to one
   * impression per session per flag id.
   *
   * @example
   * await Braze.logFeatureFlagImpression({ id: 'checkout_v2' });
   */
  logFeatureFlagImpression(options: BrazeLogFeatureFlagImpressionOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Content cards
  // ---------------------------------------------------------------------------

  /**
   * Returns all content cards currently cached for the user. Reads from
   * the SDK's local cache; call {@link BrazePlugin.requestContentCardsRefresh}
   * to force a fetch.
   *
   * @example
   * const { cards } = await Braze.getContentCards();
   * for (const card of cards) {
   *   if (card.type === 'classic') console.log(card.title);
   * }
   */
  getContentCards(): Promise<BrazeGetContentCardsResult>;

  /**
   * Requests an immediate refresh of content cards from the Braze backend.
   * Fire-and-forget: the returned promise resolves once the refresh has
   * been dispatched, **not** once new cards arrive. Use the
   * `'contentCardsUpdated'` listener to react to fresh cards, or re-read
   * via {@link BrazePlugin.getContentCards} after a short delay.
   *
   * @example
   * await Braze.requestContentCardsRefresh();
   */
  requestContentCardsRefresh(): Promise<void>;

  /**
   * Logs a click event for a content card. Call when the user taps a card
   * in your UI. Per Braze: only call when bypassing Braze's built-in
   * display module; the SDK's built-in renderer logs clicks automatically.
   *
   * @example
   * await Braze.logContentCardClick({ cardId: card.id });
   */
  logContentCardClick(options: BrazeLogContentCardClickOptions): Promise<void>;

  /**
   * Logs an impression for a content card. Call when a card scrolls into
   * view in your UI. Per Braze: only call when bypassing Braze's built-in
   * display module.
   *
   * @example
   * await Braze.logContentCardImpression({ cardId: card.id });
   */
  logContentCardImpression(options: BrazeLogContentCardImpressionOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Push token registration
  // ---------------------------------------------------------------------------

  /**
   * Hands a push registration token to the Braze SDK so the user can
   * receive Braze-orchestrated push notifications. **Native-only** —
   * the canonical wiring is:
   *
   *   1. Consumer installs `@capacitor/push-notifications` alongside this
   *      plugin.
   *   2. Consumer calls `PushNotifications.requestPermissions()` and
   *      then `PushNotifications.register()`.
   *   3. In the `registration` listener, consumer forwards the token
   *      here via `Braze.registerPushToken({ token: event.value })`.
   *
   * Platform behavior:
   *   - **iOS:** hex-decodes the APNs token and hands it to
   *     `braze.notifications.register(deviceToken:)`.
   *   - **Android:** assigns to `Braze.getInstance(context).registeredPushToken`
   *     (the SDK's setter for manual FCM token handoff).
   *   - **Web:** throws — Web Push uses VAPID + Service Worker
   *     subscriptions, with no token to register manually. See plugin
   *     MDC C03 for the divergence policy.
   *
   * @example
   * import { PushNotifications } from '@capacitor/push-notifications';
   * import { Braze } from 'capacitor-braze';
   *
   * PushNotifications.addListener('registration', async ({ value }) => {
   *   await Braze.registerPushToken({ token: value });
   * });
   */
  registerPushToken(options: BrazeRegisterPushTokenOptions): Promise<void>;

  // ---------------------------------------------------------------------------
  // Listeners
  // ---------------------------------------------------------------------------

  /**
   * Subscribes to feature flag updates. Fires whenever the Braze SDK
   * refreshes its feature flag cache — either automatically on session
   * open, manually via {@link BrazePlugin.refreshFeatureFlags}, or after
   * a server-driven sync. Initial state is not replayed when the
   * listener attaches; if you need the current snapshot, call
   * {@link BrazePlugin.getAllFeatureFlags} once after `addListener`.
   *
   * @example
   * const handle = await Braze.addListener(
   *   'featureFlagsUpdated',
   *   ({ flags }) => {
   *     console.log(`${flags.length} flags`);
   *   },
   * );
   * // Later:
   * await handle.remove();
   */
  addListener(
    eventName: 'featureFlagsUpdated',
    listenerFunc: (event: BrazeFeatureFlagsUpdatedEvent) => void,
  ): Promise<PluginListenerHandle>;

  /**
   * Subscribes to content card updates. Fires whenever the Braze SDK
   * refreshes its content card cache — either on session open, after
   * {@link BrazePlugin.requestContentCardsRefresh}, or after a
   * server-driven sync. Initial state is not replayed when the listener
   * attaches; call {@link BrazePlugin.getContentCards} once after
   * `addListener` if you need the current snapshot.
   *
   * @example
   * const handle = await Braze.addListener(
   *   'contentCardsUpdated',
   *   ({ cards }) => console.log(`${cards.length} cards`),
   * );
   */
  addListener(
    eventName: 'contentCardsUpdated',
    listenerFunc: (event: BrazeContentCardsUpdatedEvent) => void,
  ): Promise<PluginListenerHandle>;

  /**
   * Removes all listeners registered via {@link BrazePlugin.addListener}.
   * Underlying native subscriptions stay alive (managed by the plugin)
   * so adding a listener again after `removeAllListeners` works without
   * an `initialize` cycle.
   *
   * @example
   * await Braze.removeAllListeners();
   */
  removeAllListeners(): Promise<void>;

  // ---------------------------------------------------------------------------
  // Privacy / lifecycle
  // ---------------------------------------------------------------------------

  /**
   * **Destructive.** Removes all locally stored Braze SDK data on the device,
   * including the device ID and any queued unsent events.
   *
   * Typical use: GDPR Article 17 right-to-be-forgotten flow, or on user
   * logout. After wiping, you almost always also want to:
   * 1. Call your backend's Braze REST `/users/delete` to remove server-side
   *    profile data.
   * 2. Revoke the user's SDK Authentication signature.
   *
   * See `SECURITY.md` §10 for the complete privacy flow.
   *
   * Init-independent: safe to call before {@link BrazePlugin.initialize}.
   *
   * @example
   * // On logout:
   * await Braze.wipeData();
   *
   * @example
   * // Right-to-be-forgotten:
   * await Braze.wipeData();              // local
   * await myBackend.brazeDelete(userId); // server
   */
  wipeData(): Promise<void>;

  /**
   * Halts all data collection by the Braze SDK. No further events or
   * attributes are sent to Braze until {@link BrazePlugin.enableSDK} is called.
   *
   * Typical use: user revokes marketing consent under GDPR/CCPA without
   * fully wiping their data.
   *
   * Init-independent: safe to call before {@link BrazePlugin.initialize}.
   *
   * @example
   * // User opts out of marketing tracking
   * await Braze.disableSDK();
   */
  disableSDK(): Promise<void>;

  /**
   * Re-enables the Braze SDK after a {@link BrazePlugin.disableSDK} call.
   * No-op if the SDK was not previously disabled.
   *
   * Init-independent on Web and Android (both expose a class-level
   * `Braze.enableSdk` static). On iOS, BrazeKit 14.x removed the class-level
   * form — re-enabling requires an initialized `Braze` instance, so this
   * method rejects with the standard init-required error if called pre-init
   * on iOS. See `docs/mdcs/C07-INIT-INDEPENDENT-METHODS.md`.
   *
   * @example
   * // User restores consent
   * await Braze.enableSDK();
   */
  enableSDK(): Promise<void>;

  /**
   * Returns whether the SDK is currently disabled.
   *
   * Init-independent on Web and Android. On iOS BrazeKit 14.x there is no
   * class-level `isDisabled` static; this method returns `{ disabled: false }`
   * pre-init on iOS (uninitialized != disabled, by convention) and reads
   * `!braze.enabled` post-init. See `docs/mdcs/C07-INIT-INDEPENDENT-METHODS.md`.
   *
   * @example
   * const { disabled } = await Braze.isDisabled();
   * if (disabled) console.log('Tracking is paused');
   */
  isDisabled(): Promise<BrazeIsDisabledResult>;

  /**
   * Forces an immediate flush of any queued events to Braze. Normally Braze
   * batches network requests; this bypasses batching.
   *
   * Useful for: (1) Layer 4 smoke testing where you want events to appear in
   * the dashboard immediately, (2) edge cases where app may be killed before
   * the next batch.
   *
   * Requires {@link BrazePlugin.initialize} to have been called.
   *
   * @example
   * await Braze.logCustomEvent({ name: 'critical_event' });
   * await Braze.requestImmediateDataFlush(); // don't wait for batch
   */
  requestImmediateDataFlush(): Promise<void>;
}
